# Generated by Django 3.2.8 on 2021-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211119_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
