# Generated by Django 3.2.8 on 2021-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='closeDate',
            field=models.DateTimeField(),
        ),
    ]
