# Generated by Django 3.2.8 on 2021-12-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='startingPrice',
        ),
    ]
